# Generated by Django 4.2.1 on 2023-07-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=50, unique=True)),
                ('cantidadAsientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rut', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoEstimado', models.TimeField(verbose_name='Tiempo estimado')),
                ('ciudadD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='Reservar.ciudades')),
                ('ciudadO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='Reservar.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateTimeField()),
                ('cantidadPasajes', models.IntegerField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.asientos')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.bus')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios_buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('fecha', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_bus', to='Reservar.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_ruta', to='Reservar.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_asiento', to='Reservar.asientos')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_bus', to='Reservar.bus')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_fecha', to='Reservar.horarios_buses')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_horario', to='Reservar.horarios_buses')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_ruta', to='Reservar.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='asientos',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.bus'),
        ),
    ]
