# Generated by Django 4.2.1 on 2023-07-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fechaReserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horarioReserva',
            field=models.TimeField(),
        ),
    ]
