# Generated by Django 4.2.1 on 2023-07-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0002_alter_disponibilidad_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_horario', to='Reservar.horarios_buses'),
        ),
    ]
