# Generated by Django 4.2.1 on 2023-06-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0002_alter_ciudades_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientos',
            name='estado',
        ),
    ]
