# Generated by Django 4.2.1 on 2023-07-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0002_alter_reserva_fechareserva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidadPasajes',
        ),
    ]
