# Generated by Django 4.2.1 on 2023-06-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0003_remove_asientos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios_buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('fecha', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_bus', to='Reservar.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_ruta', to='Reservar.ruta')),
            ],
        ),
    ]
