# Generated by Django 4.2.1 on 2023-06-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0004_alter_bus_patente_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.destino'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.origen'),
        ),
    ]
