# Generated by Django 4.2.1 on 2023-07-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0004_alter_disponibilidad_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='apellidoM',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidoP',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
