# Generated by Django 4.2.1 on 2023-07-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0005_rename_apellido_cliente_apellidom_cliente_apellidop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
