# Generated by Django 4.2.1 on 2023-06-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0005_destino_origen_alter_ruta_destino_alter_ruta_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='destino',
            new_name='ciudadDestino',
        ),
        migrations.RenameField(
            model_name='origen',
            old_name='origen',
            new_name='ciudadOrigen',
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='destino',
            new_name='ciudadDestino',
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='origen',
            new_name='ciudadOrigen',
        ),
    ]
