# Generated by Django 4.2.1 on 2023-06-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0006_rename_destino_destino_ciudaddestino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='tiempoEstimado',
            field=models.TimeField(max_length=100),
        ),
    ]
