# Generated by Django 4.2.1 on 2023-06-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0007_alter_ruta_tiempoestimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='tiempoEstimado',
            field=models.TimeField(verbose_name='Tiempo estimado'),
        ),
    ]
