# Generated by Django 4.2.1 on 2023-07-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0007_remove_reserva_ruta_reserva_ciudadd_reserva_ciudado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fechaReserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horarioReserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_fecha', to='Reservar.disponibilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_horario', to='Reservar.disponibilidad'),
            preserve_default=False,
        ),
    ]
