# Generated by Django 4.2.1 on 2023-06-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0008_alter_ruta_tiempoestimado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='ciudadDestino',
            new_name='ciudadD',
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='ciudadOrigen',
            new_name='ciudadO',
        ),
    ]
