# Generated by Django 4.2.1 on 2023-07-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0008_alter_ruta_ciudadd_alter_ruta_ciudado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='horarios_buses',
            name='ruta',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='ciudadD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_ciudadD', to='Reservar.ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='ciudadO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_ciudadO', to='Reservar.ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarios_buses',
            name='ciudadD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_ciudadD', to='Reservar.ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarios_buses',
            name='ciudadO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_ciudadO', to='Reservar.ruta'),
            preserve_default=False,
        ),
    ]
