# Generated by Django 4.2.1 on 2023-07-17 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0008_remove_reserva_fechareserva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='horarios_buses',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_fecha', to='Reservar.fecha'),
        ),
        migrations.AlterField(
            model_name='horarios_buses',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_buses_horario', to='Reservar.horario'),
        ),
    ]
