# Generated by Django 4.2.1 on 2023-07-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0009_fecha_horario_alter_horarios_buses_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='disponible',
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_fecha', to='Reservar.fecha'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_horario', to='Reservar.horario'),
        ),
    ]
