# Generated by Django 4.2.1 on 2023-07-06 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0009_remove_disponibilidad_ruta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarios_buses',
            old_name='ciudadO',
            new_name='ruta',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='ciudadD',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='ciudadO',
        ),
        migrations.RemoveField(
            model_name='horarios_buses',
            name='ciudadD',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_ruta', to='Reservar.ruta'),
            preserve_default=False,
        ),
    ]
