# Generated by Django 4.2.1 on 2023-07-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0011_disponibilidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='horarios_buses',
            name='ruta',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='ciudadD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_destino', to='Reservar.ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='ciudadO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_origen', to='Reservar.ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarios_buses',
            name='ciudadD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_destino', to='Reservar.ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarios_buses',
            name='ciudadO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_origen', to='Reservar.ruta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.bus'),
        ),
        migrations.AlterField(
            model_name='horarios_buses',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.bus'),
        ),
        migrations.AlterField(
            model_name='horarios_buses',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horarios_buses_horario', to='Reservar.horario'),
        ),
    ]
