# Generated by Django 4.2.1 on 2023-06-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=50)),
                ('cantidadAsientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tiempoEstimado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateTimeField()),
                ('cantidadPasajes', models.IntegerField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.asientos')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.bus')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_asiento', to='Reservar.asientos')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_bus', to='Reservar.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_ruta', to='Reservar.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='asientos',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservar.bus'),
        ),
    ]
